# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_icon'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together=set([('slug', 'category')]),
        ),
    ]
