# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-03 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170802_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='extend',
            field=models.TextField(blank=True, verbose_name='Extendido'),
        ),
    ]
